// Generated by design-system/scripts/sync_contentful_design_library_sources.py.
// Source: Design System/tokens/brands/immoscout24.json
// LP module sources are listed in lp-module-markup.js and lp-shadow-styles.js.
// Do not edit manually.
window.designLibraryData = {
  "sections": {
    "lp": {
      "label": "LP Builder",
      "items": [
        {
          "id": "heros",
          "label": "Heros",
          "kind": "lpModules",
          "modules": [
            "hero-bleed-flex",
            "hero-bleed-flex-centered",
            "hero-split"
          ]
        },
        {
          "id": "teaser",
          "label": "Teaser",
          "kind": "lpModules",
          "modules": [
            "teaser-2col",
            "teaser-3col",
            "teaser-4col",
            "teaser-split-image-right",
            "teaser-split-image-left",
            "teaser-split-colour-image-right",
            "teaser-split-colour-image-left",
            "pricing-list",
            "choice-card-list",
            "choice-card-expand-list",
            "content-cards-2col",
            "content-cards-3col",
            "card-carousel"
          ]
        },
        {
          "id": "process",
          "label": "Process",
          "kind": "lpModules",
          "modules": [
            "steps-3col",
            "steps-4col"
          ]
        },
        {
          "id": "text-lists",
          "label": "Text & Lists",
          "kind": "lpElements",
          "modules": [],
          "elementGroups": [
            {
              "label": "Text",
              "layout": "stack",
              "elements": [
                "headline-variants",
                "text-variants",
                "text-links"
              ]
            },
            {
              "label": "Lists",
              "layout": "grid",
              "elements": [
                "list-ordered",
                "list-bullet",
                "checkmark-list",
                "list-nested"
              ]
            }
          ]
        },
        {
          "id": "buttons-links",
          "label": "Buttons & Links",
          "kind": "lpElements",
          "modules": [],
          "elementGroups": [
            {
              "label": "Buttons & Links",
              "layout": "inline",
              "elements": [
                "button-filled-brand",
                "button-filled-default",
                "button-outline-strong",
                "button-outline-weak",
                "lpb-button--mobile-full",
                "chevron-link"
              ]
            }
          ]
        },
        {
          "id": "video",
          "label": "Video",
          "kind": "lpModules",
          "modules": [
            "video--youtube"
          ]
        },
        {
          "id": "counter",
          "label": "Counter",
          "kind": "lpModules",
          "modules": [
            "counter-animated"
          ]
        },
        {
          "id": "callouts",
          "label": "Callouts",
          "kind": "lpModules",
          "modules": [
            "callout--base",
            "callout--illu",
            "callout--expert"
          ]
        },
        {
          "id": "colors",
          "label": "Colors",
          "kind": "lpElements",
          "modules": [],
          "elementGroups": [
            {
              "label": "Accent Colors",
              "layout": "colors",
              "elements": [
                "accent-teal",
                "accent-yellow",
                "accent-blue",
                "accent-purple",
                "accent-orange"
              ]
            },
            {
              "label": "Neutrals",
              "layout": "colors",
              "elements": [
                "neutral-charcoal",
                "neutral-white",
                "neutral-sand",
                "neutral-grey-1",
                "neutral-grey-2",
                "neutral-grey-3",
                "neutral-grey-4",
                "neutral-grey-5",
                "neutral-grey-6"
              ]
            },
            {
              "label": "Text Colors",
              "layout": "colors",
              "elements": [
                "text-charcoal",
                "text-white-inversive",
                "text-muted"
              ]
            },
            {
              "label": "Semantic Surfaces",
              "layout": "colors",
              "elements": [
                "surface-brand",
                "surface-default",
                "surface-weak"
              ]
            }
          ]
        },
        {
          "id": "action-tiles",
          "label": "Action Tiles",
          "kind": "lpModules",
          "modules": []
        },
        {
          "id": "team-professional",
          "label": "Team Professional",
          "kind": "lpModules",
          "modules": []
        },
        {
          "id": "accordion",
          "label": "Accordion",
          "kind": "lpModules",
          "modules": []
        },
        {
          "id": "benefits",
          "label": "Benefits",
          "kind": "lpModules",
          "modules": []
        },
        {
          "id": "service-tiles",
          "label": "Service Tiles",
          "kind": "lpModules",
          "modules": []
        },
        {
          "id": "tables",
          "label": "Tables",
          "kind": "lpModules",
          "modules": []
        },
        {
          "id": "sticky-footer",
          "label": "Sticky Footer",
          "kind": "lpModules",
          "modules": []
        }
      ]
    },
    "tokens": {
      "label": "Design Tokens",
      "items": [
        {
          "id": "colors",
          "label": "Colors",
          "kind": "tokens"
        },
        {
          "id": "typography",
          "label": "Typography",
          "kind": "tokens"
        },
        {
          "id": "spacing",
          "label": "Spacing",
          "kind": "tokens"
        },
        {
          "id": "radius",
          "label": "Border Radius",
          "kind": "tokens"
        },
        {
          "id": "borders",
          "label": "Borders",
          "kind": "tokens"
        },
        {
          "id": "ratios",
          "label": "Image Ratios",
          "kind": "tokens"
        }
      ]
    }
  },
  "lpElements": {
    "headline-variants": {
      "markup": "<div data-lpb-component=\"headline-variants\"><p class=\"font-heading-xlarge-regular\">Heading XLarge Regular</p><p class=\"font-heading-xlarge-bold\">Heading XLarge Bold</p><p class=\"font-heading-large-regular\">Heading Large Regular</p><p class=\"font-heading-large-bold\">Heading Large Bold</p><p class=\"font-heading-medium-regular\">Heading Medium Regular</p><p class=\"font-heading-medium-bold\">Heading Medium Bold</p><p class=\"font-heading-small-regular\">Heading Small Regular</p><p class=\"font-heading-small-bold\">Heading Small Bold</p><p class=\"font-heading-xsmall-regular\">Heading XSmall Regular</p><p class=\"font-heading-xsmall-bold\">Heading XSmall Bold</p></div>",
      "copyPayload": "<div data-lpb-component=\"headline-variants\"><p class=\"font-heading-xlarge-regular\">Heading XLarge Regular</p><p class=\"font-heading-xlarge-bold\">Heading XLarge Bold</p><p class=\"font-heading-large-regular\">Heading Large Regular</p><p class=\"font-heading-large-bold\">Heading Large Bold</p><p class=\"font-heading-medium-regular\">Heading Medium Regular</p><p class=\"font-heading-medium-bold\">Heading Medium Bold</p><p class=\"font-heading-small-regular\">Heading Small Regular</p><p class=\"font-heading-small-bold\">Heading Small Bold</p><p class=\"font-heading-xsmall-regular\">Heading XSmall Regular</p><p class=\"font-heading-xsmall-bold\">Heading XSmall Bold</p></div>",
      "copyLabel": "headline-variants"
    },
    "text-variants": {
      "markup": "<div data-lpb-component=\"text-variants\"><p class=\"font-body-large-regular\">Body Large Regular</p><p class=\"font-body-large-bold\">Body Large Bold</p><p class=\"font-body-medium-regular\">Body Medium Regular</p><p class=\"font-body-medium-bold\">Body Medium Bold</p><p class=\"font-body-small-regular\">Body Small Regular</p><p class=\"font-body-small-bold\">Body Small Bold</p></div>",
      "copyPayload": "<div data-lpb-component=\"text-variants\"><p class=\"font-body-large-regular\">Body Large Regular</p><p class=\"font-body-large-bold\">Body Large Bold</p><p class=\"font-body-medium-regular\">Body Medium Regular</p><p class=\"font-body-medium-bold\">Body Medium Bold</p><p class=\"font-body-small-regular\">Body Small Regular</p><p class=\"font-body-small-bold\">Body Small Bold</p></div>",
      "copyLabel": "text-variants"
    },
    "text-links": {
      "markup": "<div id=\"example-target\" data-lpb-component=\"text-links\" class=\"font-body-large-regular\"><p>Text with an <a href=\"/example\">internal inline link</a>.</p><p><a href=\"/example\">Standalone internal text link</a></p><p><a href=\"https://example.com\" target=\"_blank\" rel=\"noopener noreferrer\">External link in a new tab</a></p><p><a href=\"#example-target\">Anchor link</a> · <a href=\"mailto:example@example.com\">Email</a> · <a href=\"tel:+493012345678\">Phone</a></p></div>",
      "copyPayload": "<div id=\"example-target\" data-lpb-component=\"text-links\" class=\"font-body-large-regular\"><p>Text with an <a href=\"/example\">internal inline link</a>.</p><p><a href=\"/example\">Standalone internal text link</a></p><p><a href=\"https://example.com\" target=\"_blank\" rel=\"noopener noreferrer\">External link in a new tab</a></p><p><a href=\"#example-target\">Anchor link</a> · <a href=\"mailto:example@example.com\">Email</a> · <a href=\"tel:+493012345678\">Phone</a></p></div>",
      "copyLabel": "text-links"
    },
    "list-ordered": {
      "markup": "<div data-lpb-component=\"list-ordered\"><ol class=\"font-body-large-regular\"><li>First step</li><li>Second step</li><li>Third step</li></ol></div>",
      "copyPayload": "<div data-lpb-component=\"list-ordered\"><ol class=\"font-body-large-regular\"><li>First step</li><li>Second step</li><li>Third step</li></ol></div>",
      "copyLabel": "Numbered List"
    },
    "list-bullet": {
      "markup": "<div data-lpb-component=\"list-bullet\"><ul class=\"list-bullet font-body-large-regular\"><li>Short benefit one</li><li>Short benefit two</li><li>Short benefit three</li></ul></div>",
      "copyPayload": "<div data-lpb-component=\"list-bullet\"><ul class=\"list-bullet font-body-large-regular\"><li>Short benefit one</li><li>Short benefit two</li><li>Short benefit three</li></ul></div>",
      "copyLabel": "Bullet List"
    },
    "checkmark-list": {
      "markup": "<div data-lpb-component=\"checkmark-list\"><ul class=\"checkmark-list\"><li class=\"checkmark-list__item\"><span class=\"checkmark-list__icon\" aria-hidden=\"true\"></span><span class=\"checkmark-list__text font-body-large-regular\">Alle wichtigen Informationen bleiben übersichtlich an einem Ort.</span></li><li class=\"checkmark-list__item\"><span class=\"checkmark-list__icon\" aria-hidden=\"true\"></span><span class=\"checkmark-list__text font-body-large-regular\">Sie treffen Entscheidungen auf einer nachvollziehbaren Grundlage.</span></li><li class=\"checkmark-list__item\"><span class=\"checkmark-list__icon\" aria-hidden=\"true\"></span><span class=\"checkmark-list__text font-body-large-regular\">Passende Services unterstützen Sie bei jedem nächsten Schritt.</span></li></ul></div>",
      "copyPayload": "<div data-lpb-component=\"checkmark-list\"><ul class=\"checkmark-list\"><li class=\"checkmark-list__item\"><span class=\"checkmark-list__icon\" aria-hidden=\"true\"></span><span class=\"checkmark-list__text font-body-large-regular\">Alle wichtigen Informationen bleiben übersichtlich an einem Ort.</span></li><li class=\"checkmark-list__item\"><span class=\"checkmark-list__icon\" aria-hidden=\"true\"></span><span class=\"checkmark-list__text font-body-large-regular\">Sie treffen Entscheidungen auf einer nachvollziehbaren Grundlage.</span></li><li class=\"checkmark-list__item\"><span class=\"checkmark-list__icon\" aria-hidden=\"true\"></span><span class=\"checkmark-list__text font-body-large-regular\">Passende Services unterstützen Sie bei jedem nächsten Schritt.</span></li></ul></div>",
      "copyLabel": "Checkmark List"
    },
    "list-nested": {
      "markup": "<div data-lpb-component=\"list-nested\"><ul class=\"font-body-large-regular\"><li>Parent item<ul><li>Child item one</li><li>Child item two</li></ul></li><li>Second parent item</li></ul></div>",
      "copyPayload": "<div data-lpb-component=\"list-nested\"><ul class=\"font-body-large-regular\"><li>Parent item<ul><li>Child item one</li><li>Child item two</li></ul></li><li>Second parent item</li></ul></div>",
      "copyLabel": "Nested Bullet List"
    },
    "button-filled-brand": {
      "markup": "<a class=\"lpb-button lpb-button--filled-brand\" href=\"#\">Button label</a>",
      "copyPayload": "<a class=\"lpb-button lpb-button--filled-brand\" href=\"#\">Button label</a>",
      "copyLabel": "button-filled-brand"
    },
    "button-filled-default": {
      "markup": "<a class=\"lpb-button lpb-button--filled-default\" href=\"#\">Button label</a>",
      "copyPayload": "<a class=\"lpb-button lpb-button--filled-default\" href=\"#\">Button label</a>",
      "copyLabel": "button-filled-default"
    },
    "button-outline-strong": {
      "markup": "<a class=\"lpb-button lpb-button--outline-strong\" href=\"#\">Button label</a>",
      "copyPayload": "<a class=\"lpb-button lpb-button--outline-strong\" href=\"#\">Button label</a>",
      "copyLabel": "button-outline-strong"
    },
    "button-outline-weak": {
      "markup": "<a class=\"lpb-button lpb-button--outline-weak\" href=\"#\">Button label</a>",
      "copyPayload": "<a class=\"lpb-button lpb-button--outline-weak\" href=\"#\">Button label</a>",
      "copyLabel": "button-outline-weak"
    },
    "lpb-button--mobile-full": {
      "markup": "<a class=\"lpb-button lpb-button--filled-brand lpb-button--mobile-full\" href=\"#\">Mobile Full Width Button</a>",
      "copyPayload": "<a class=\"lpb-button lpb-button--filled-brand lpb-button--mobile-full\" href=\"#\">Mobile Full Width Button</a>",
      "copyLabel": "Mobile Full Width Button"
    },
    "chevron-link": {
      "markup": "<div data-lpb-component=\"chevron-link\"><a class=\"lpb-chevron-link\" href=\"/example\"><img class=\"lpb-chevron-link__icon\" src=\"https://www.immobilienscout24.de/content/dam/claude-lp-creator/assets/Chevron.svg\" alt=\"\" width=\"16\" height=\"16\" loading=\"lazy\"><span>Mehr erfahren</span></a></div>",
      "copyPayload": "<div data-lpb-component=\"chevron-link\"><a class=\"lpb-chevron-link\" href=\"/example\"><img class=\"lpb-chevron-link__icon\" src=\"https://www.immobilienscout24.de/content/dam/claude-lp-creator/assets/Chevron.svg\" alt=\"\" width=\"16\" height=\"16\" loading=\"lazy\"><span>Mehr erfahren</span></a></div>",
      "copyLabel": "Chevron Link"
    },
    "accent-teal": {
      "markup": "<div class=\"library-swatch lpb-color-bg--teal lpb-color-text--charcoal\"><span class=\"font-body-medium-bold\">teal</span></div>",
      "copyPayload": "lpb-color-bg--teal lpb-color-text--charcoal",
      "copyLabel": "teal"
    },
    "accent-yellow": {
      "markup": "<div class=\"library-swatch lpb-color-bg--yellow lpb-color-text--charcoal\"><span class=\"font-body-medium-bold\">yellow</span></div>",
      "copyPayload": "lpb-color-bg--yellow lpb-color-text--charcoal",
      "copyLabel": "yellow"
    },
    "accent-blue": {
      "markup": "<div class=\"library-swatch lpb-color-bg--blue lpb-color-text--charcoal\"><span class=\"font-body-medium-bold\">blue</span></div>",
      "copyPayload": "lpb-color-bg--blue lpb-color-text--charcoal",
      "copyLabel": "blue"
    },
    "accent-purple": {
      "markup": "<div class=\"library-swatch lpb-color-bg--purple lpb-color-text--charcoal\"><span class=\"font-body-medium-bold\">purple</span></div>",
      "copyPayload": "lpb-color-bg--purple lpb-color-text--charcoal",
      "copyLabel": "purple"
    },
    "accent-orange": {
      "markup": "<div class=\"library-swatch lpb-color-bg--orange lpb-color-text--charcoal\"><span class=\"font-body-medium-bold\">orange</span></div>",
      "copyPayload": "lpb-color-bg--orange lpb-color-text--charcoal",
      "copyLabel": "orange"
    },
    "neutral-charcoal": {
      "markup": "<div class=\"library-swatch lpb-color-bg--charcoal lpb-color-text--white\"><span class=\"font-body-medium-bold\">charcoal</span></div>",
      "copyPayload": "lpb-color-bg--charcoal lpb-color-text--white",
      "copyLabel": "charcoal"
    },
    "neutral-white": {
      "markup": "<div class=\"library-swatch lpb-color-bg--white lpb-color-text--charcoal\"><span class=\"font-body-medium-bold\">white</span></div>",
      "copyPayload": "lpb-color-bg--white lpb-color-text--charcoal",
      "copyLabel": "white"
    },
    "neutral-sand": {
      "markup": "<div class=\"library-swatch lpb-color-bg--sand lpb-color-text--charcoal\"><span class=\"font-body-medium-bold\">sand</span></div>",
      "copyPayload": "lpb-color-bg--sand lpb-color-text--charcoal",
      "copyLabel": "sand"
    },
    "neutral-grey-1": {
      "markup": "<div class=\"library-swatch lpb-color-bg--grey-1 lpb-color-text--charcoal\"><span class=\"font-body-medium-bold\">grey-1</span></div>",
      "copyPayload": "lpb-color-bg--grey-1 lpb-color-text--charcoal",
      "copyLabel": "grey-1"
    },
    "neutral-grey-2": {
      "markup": "<div class=\"library-swatch lpb-color-bg--grey-2 lpb-color-text--charcoal\"><span class=\"font-body-medium-bold\">grey-2</span></div>",
      "copyPayload": "lpb-color-bg--grey-2 lpb-color-text--charcoal",
      "copyLabel": "grey-2"
    },
    "neutral-grey-3": {
      "markup": "<div class=\"library-swatch lpb-color-bg--grey-3 lpb-color-text--charcoal\"><span class=\"font-body-medium-bold\">grey-3</span></div>",
      "copyPayload": "lpb-color-bg--grey-3 lpb-color-text--charcoal",
      "copyLabel": "grey-3"
    },
    "neutral-grey-4": {
      "markup": "<div class=\"library-swatch lpb-color-bg--grey-4 lpb-color-text--charcoal\"><span class=\"font-body-medium-bold\">grey-4</span></div>",
      "copyPayload": "lpb-color-bg--grey-4 lpb-color-text--charcoal",
      "copyLabel": "grey-4"
    },
    "neutral-grey-5": {
      "markup": "<div class=\"library-swatch lpb-color-bg--grey-5 lpb-color-text--charcoal\"><span class=\"font-body-medium-bold\">grey-5</span></div>",
      "copyPayload": "lpb-color-bg--grey-5 lpb-color-text--charcoal",
      "copyLabel": "grey-5"
    },
    "neutral-grey-6": {
      "markup": "<div class=\"library-swatch lpb-color-bg--grey-6 lpb-color-text--white\"><span class=\"font-body-medium-bold\">grey-6</span></div>",
      "copyPayload": "lpb-color-bg--grey-6 lpb-color-text--white",
      "copyLabel": "grey-6"
    },
    "text-charcoal": {
      "markup": "<div class=\"library-text-sample lpb-color-text--charcoal\"><span class=\"font-body-large-regular\">charcoal</span></div>",
      "copyPayload": "lpb-color-text--charcoal",
      "copyLabel": "charcoal"
    },
    "text-white-inversive": {
      "markup": "<div class=\"library-text-sample library-text-sample--inverse lpb-color-bg--charcoal lpb-color-text--white\"><span class=\"font-body-large-regular\">white / inversive</span></div>",
      "copyPayload": "lpb-color-bg--charcoal lpb-color-text--white",
      "copyLabel": "white / inversive"
    },
    "text-muted": {
      "markup": "<div class=\"library-text-sample lpb-color-text--muted\"><span class=\"font-body-large-regular\">muted</span></div>",
      "copyPayload": "lpb-color-text--muted",
      "copyLabel": "muted"
    },
    "surface-brand": {
      "markup": "<div class=\"library-surface lpb-surface--brand lpb-text--default\"><span class=\"font-body-medium-bold\">brand</span></div>",
      "copyPayload": "lpb-surface--brand lpb-text--default",
      "copyLabel": "brand"
    },
    "surface-default": {
      "markup": "<div class=\"library-surface lpb-surface--default lpb-text--default border\"><span class=\"font-body-medium-bold\">default</span></div>",
      "copyPayload": "lpb-surface--default lpb-text--default border",
      "copyLabel": "default"
    },
    "surface-weak": {
      "markup": "<div class=\"library-surface lpb-surface--weak lpb-text--default\"><span class=\"font-body-medium-bold\">weak</span></div>",
      "copyPayload": "lpb-surface--weak lpb-text--default",
      "copyLabel": "weak"
    }
  },
  "tokens": {
    "colors": {
      "groups": [
        {
          "title": "Accent Colors",
          "items": [
            {
              "name": "Teal",
              "value": "#3DF5DC"
            },
            {
              "name": "Yellow",
              "value": "#EFF933"
            },
            {
              "name": "Blue",
              "value": "#24E3FF"
            },
            {
              "name": "Purple",
              "value": "#D5AAFF"
            },
            {
              "name": "Orange",
              "value": "#FF9626"
            }
          ]
        },
        {
          "title": "Neutrals",
          "items": [
            {
              "name": "Charcoal",
              "value": "#333333"
            },
            {
              "name": "White",
              "value": "#FFFFFF"
            },
            {
              "name": "Sand",
              "value": "#FBF8F6"
            },
            {
              "name": "Grey 1",
              "value": "#F5F5F5"
            },
            {
              "name": "Grey 2",
              "value": "#EAEAEA"
            },
            {
              "name": "Grey 3",
              "value": "#E0E0E0"
            },
            {
              "name": "Grey 4",
              "value": "#C4C4C4"
            },
            {
              "name": "Grey 5",
              "value": "#ADADAD"
            },
            {
              "name": "Grey 6",
              "value": "#676767"
            }
          ]
        },
        {
          "title": "Semantic LP Colors",
          "items": [
            {
              "name": "hoverTeal",
              "value": "#55E6CB"
            },
            {
              "name": "hoverCharcoal",
              "value": "#484848"
            },
            {
              "name": "hoverSand",
              "value": "#FBF8F6"
            },
            {
              "name": "hoverSoft",
              "value": "#E8E5E3"
            },
            {
              "name": "borderSoft",
              "value": "#E0E0E0"
            },
            {
              "name": "borderWeak",
              "value": "#BDBBB9"
            },
            {
              "name": "textMuted",
              "value": "#6A6A69"
            },
            {
              "name": "mediaPlaceholder",
              "value": "#EAEAEA"
            }
          ]
        }
      ]
    },
    "typography": {
      "sample": "Make It Better",
      "sourceLabel": "makeitbetter.css",
      "sourceUrl": "https://www.static-immobilienscout24.de/fro/make-it-better/1.0.0/makeitbetter.css",
      "headingItems": [
        {
          "name": "heading-xxl",
          "label": "Heading XXL bold",
          "desktop": {
            "fontSize": "60px",
            "lineHeight": "72px"
          },
          "mobile": {
            "fontSize": "40px",
            "lineHeight": "48px"
          }
        },
        {
          "name": "heading-xl",
          "label": "Heading XL bold",
          "desktop": {
            "fontSize": "48px",
            "lineHeight": "58px"
          },
          "mobile": {
            "fontSize": "32px",
            "lineHeight": "40px"
          }
        },
        {
          "name": "heading-l",
          "label": "Heading L bold",
          "desktop": {
            "fontSize": "34px",
            "lineHeight": "44px"
          },
          "mobile": {
            "fontSize": "28px",
            "lineHeight": "36px"
          }
        },
        {
          "name": "heading-m",
          "label": "Heading M bold",
          "desktop": {
            "fontSize": "26px",
            "lineHeight": "36px"
          },
          "mobile": {
            "fontSize": "24px",
            "lineHeight": "34px"
          }
        },
        {
          "name": "heading-s",
          "label": "Heading S bold",
          "desktop": {
            "fontSize": "20px",
            "lineHeight": "30px"
          },
          "mobile": {
            "fontSize": "20px",
            "lineHeight": "30px"
          }
        },
        {
          "name": "heading-xs",
          "label": "Heading XS bold",
          "desktop": {
            "fontSize": "18px",
            "lineHeight": "28px"
          },
          "mobile": {
            "fontSize": "18px",
            "lineHeight": "28px"
          }
        }
      ],
      "bodyItems": [
        {
          "name": "body-standard",
          "label": "P Standard",
          "desktop": {
            "fontSize": "16px",
            "lineHeight": "24px"
          },
          "mobile": {
            "fontSize": "16px",
            "lineHeight": "24px"
          }
        },
        {
          "name": "body-tabular",
          "label": "P Tabular",
          "desktop": {
            "fontSize": "16px",
            "lineHeight": "22px"
          },
          "mobile": {
            "fontSize": "16px",
            "lineHeight": "22px"
          }
        },
        {
          "name": "body-hint",
          "label": "P Hint",
          "desktop": {
            "fontSize": "12px",
            "lineHeight": "18px"
          },
          "mobile": {
            "fontSize": "12px",
            "lineHeight": "18px"
          }
        }
      ]
    },
    "radius": [
      {
        "name": "none",
        "value": "0"
      },
      {
        "name": "2",
        "value": "2px"
      },
      {
        "name": "4",
        "value": "4px"
      },
      {
        "name": "8",
        "value": "8px"
      },
      {
        "name": "12",
        "value": "12px"
      },
      {
        "name": "16",
        "value": "16px"
      },
      {
        "name": "24",
        "value": "24px"
      },
      {
        "name": "40",
        "value": "40px"
      },
      {
        "name": "pill",
        "value": "999px"
      }
    ],
    "spacing": [
      {
        "name": "spacing-100",
        "value": "4px"
      },
      {
        "name": "spacing-200",
        "value": "8px"
      },
      {
        "name": "spacing-300",
        "value": "12px"
      },
      {
        "name": "spacing-400",
        "value": "16px"
      },
      {
        "name": "spacing-600",
        "value": "24px"
      },
      {
        "name": "spacing-800",
        "value": "32px"
      },
      {
        "name": "spacing-1000",
        "value": "40px"
      },
      {
        "name": "spacing-1500",
        "value": "60px"
      }
    ],
    "borders": [
      {
        "name": "none",
        "value": "0"
      },
      {
        "name": "thin",
        "value": "1px"
      }
    ],
    "ratios": [
      {
        "ratio": "16:9",
        "title": "16:9",
        "primarySize": "1200 x 675 px",
        "secondarySize": "2400 x 1350 px",
        "usage": "LP Hero Split",
        "badge": ""
      },
      {
        "ratio": "4:3",
        "title": "4:3",
        "primarySize": "",
        "secondarySize": "",
        "usage": "Canonical image ratio",
        "badge": ""
      }
    ]
  }
};
