#!/usr/bin/env python3

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path
from typing import Any


PROJECT_ROOT = Path(__file__).resolve().parents[2]
LP_BUILDER_DIR = PROJECT_ROOT / "lp-builder"
DESIGN_LIBRARY_DIR = PROJECT_ROOT / "design-system" / "design-library"

COMPONENT_LIBRARY_PATH = LP_BUILDER_DIR / "knowledge" / "component-library.html"
MODULE_METADATA_PATH = LP_BUILDER_DIR / "knowledge" / "module-metadata.json"
LP_MARKUP_PATH = DESIGN_LIBRARY_DIR / "lp-module-markup.js"
LP_SHADOW_STYLES_PATH = DESIGN_LIBRARY_DIR / "lp-shadow-styles.js"
CONTENT_DATA_PATH = DESIGN_LIBRARY_DIR / "content-data.js"
LP_LEGACY_UTILITIES_PATH = DESIGN_LIBRARY_DIR / "lp-legacy-utilities.css"

LP_CORE_STYLE_SOURCES = [
    LP_BUILDER_DIR / "runtime" / "core" / "core-foundations.css",
    LP_BUILDER_DIR / "runtime" / "core" / "core-buttons.css",
    LP_BUILDER_DIR / "runtime" / "core" / "core-components.css",
]

LP_MARKUP_MARKER = "window.designLibraryLpModuleMarkup = "
LP_SHADOW_MARKER = "window.designLibraryLpShadowCss = "
CONTENT_DATA_MARKER = "window.designLibraryData = "
GENERATED_HEADER = (
    "// Generated by design-system/scripts/sync_lp_builder_to_design_library.py.\n"
    f"// Source: {COMPONENT_LIBRARY_PATH.relative_to(PROJECT_ROOT).as_posix()}\n"
    f"// Source: {MODULE_METADATA_PATH.relative_to(PROJECT_ROOT).as_posix()}\n"
    "// Do not edit manually.\n"
)
GENERATED_CSS_HEADER = (
    "// Generated by design-system/scripts/sync_lp_builder_to_design_library.py.\n"
    f"// Source: {LP_LEGACY_UTILITIES_PATH.relative_to(PROJECT_ROOT).as_posix()}\n"
    + "".join(f"// Source: {path.relative_to(PROJECT_ROOT).as_posix()}\n" for path in LP_CORE_STYLE_SOURCES)
    + "// Source: embedded LP preview frame styles for the Design Library.\n"
    "// Do not edit manually.\n"
)

LEGACY_LP_PAGE_SPECS = [
    {"id": "lp-heros", "label": "Heros", "modules": ["hero-split", "hero-bleed-flex", "hero-bleed-flex-centered"]},
    {
        "id": "lp-teaser",
        "label": "Teaser",
        "modules": ["teaser-2col", "teaser-3col", "teaser-4col", "teaser-split-image-right", "teaser-split-image-left"],
    },
    {"id": "lp-steps", "label": "Steps", "modules": ["steps-3col", "steps-4col"]},
    {"id": "lp-accordion", "label": "Accordion", "modules": ["accordion"]},
    {"id": "lp-counter", "label": "Counter", "modules": ["counter-animated"]},
    {"id": "lp-callouts", "label": "Callouts", "modules": ["callout--base", "callout--illu", "callout--expert"]},
    {"id": "lp-benefits", "label": "Benefits", "modules": ["benefits-3col", "benefits-2col"]},
    {"id": "lp-reviews", "label": "Reviews", "modules": ["ekomi-reviews"]},
    {"id": "lp-service-tiles", "label": "Service Tiles", "modules": ["servicetiles"]},
    {"id": "lp-checkmark-list", "label": "Checkmark List", "modules": ["checkmark-list"]},
    {"id": "lp-sticky-footer", "label": "Sticky Footer", "modules": ["lp-sticky-footer"]},
    {"id": "lp-content-cards", "label": "Content Cards", "modules": ["content-cards-2col", "content-cards-3col"]},
    {"id": "lp-pricing-list", "label": "Pricing List", "modules": ["pricing-list"]},
    {"id": "lp-action-tiles", "label": "Action Tiles", "modules": ["action-tiles_rle"]},
    {"id": "lp-video", "label": "Video", "modules": ["video--youtube"]},
]

EMBEDDED_PREVIEW_FRAME_CSS = """\
:root {
  --module-content-max: 1170px;
  --module-content-max-mobile: 374px;
}

* {
  box-sizing: border-box;
}

html,
body {
  margin: 0;
  padding: 0;
  background: transparent;
}

body,
.frame-root,
.frame-root a,
.frame-root button,
.frame-root input,
.frame-root select,
.frame-root textarea {
  font-family: "Make It Better", Verdana, "DejaVu Sans", Arial, Helvetica, sans-serif;
}

body {
  color: #333333;
}

.frame-root {
  width: 100%;
}

.frame-root > * {
  width: min(100%, var(--module-content-max));
  margin-left: auto;
  margin-right: auto;
}

:host([data-lp-page="lp-heros"]) .frame-root > * {
  width: 100%;
  margin-left: 0;
  margin-right: 0;
}

:host([data-lp-page="lp-action-tiles"]) .frame-root > * {
  width: 100%;
  margin-left: 0;
  margin-right: 0;
}

.frame-root > .grid.gutter,
.frame-root > .grid.grid-flex.gutter {
  width: calc(min(100%, var(--module-content-max)) - 24px);
}

.frame-root > .hero-split,
.frame-root > .hero-bleed-flex,
.frame-root > .hero-bleed-flex-centered,
.frame-root > .teaser,
.frame-root > .teaser-split,
.frame-root > .lp-full-bleed,
.frame-root > .counter-animated,
.frame-root > .content-cards-2col,
.frame-root > .content-cards-3col,
.frame-root > .video-module {
  width: 100%;
  margin-left: 0;
  margin-right: 0;
}

.frame-root > .lp-full-bleed .lp-full-bleed__inner {
  width: min(100%, var(--module-content-max));
  margin-left: auto;
  margin-right: auto;
}

/*
  Preview-only bleed containment:
  LP modules may use viewport-wide backgrounds in production.
  Inside the Design Library they must stay inside the content column
  instead of painting underneath the sidebar.
*/
.frame-root .hero-bleed-flex__image,
.frame-root .hero-bleed-flex-centered__image,
.frame-root .hero-bleed__image,
.frame-root .hero-bleed-centered__image {
  width: 100% !important;
  margin-left: 0 !important;
  margin-right: 0 !important;
}

:host([data-lp-page="lp-heros"]) .frame-root .hero-bleed-flex__content {
  padding-inline: 24px;
  box-sizing: border-box;
}

.frame-root .lp-full-bleed::before,
.frame-root .lp-sticky-footer::before {
  width: 100% !important;
  left: 0 !important;
  transform: none !important;
}

.lp-media__inner {
  background: #EAEAEA;
}

.lp-media__inner::before {
  content: none !important;
}

img[src=""] {
  visibility: hidden;
}

.lp-sticky-footer {
  position: static !important;
  right: auto !important;
  bottom: auto !important;
  left: auto !important;
}

.counter-animated__item .font-heading-xlarge-bold {
  font-weight: 700;
}

@media (max-width: 740px) {
  .frame-root > * {
    width: min(100%, var(--module-content-max-mobile));
  }

  :host([data-lp-page="lp-heros"]) .frame-root > * {
    width: 100%;
    margin-left: 0;
    margin-right: 0;
  }

  :host([data-lp-page="lp-action-tiles"]) .frame-root > * {
    width: 100%;
    margin-left: 0;
    margin-right: 0;
  }

  .frame-root > .grid.gutter,
  .frame-root > .grid.grid-flex.gutter {
    width: calc(min(100%, var(--module-content-max-mobile)) - 24px);
  }

  .frame-root > .hero-split,
  .frame-root > .hero-bleed-flex,
  .frame-root > .hero-bleed-flex-centered,
  .frame-root > .teaser,
  .frame-root > .teaser-split,
  .frame-root > .lp-full-bleed,
  .frame-root > .counter-animated,
  .frame-root > .content-cards-2col,
  .frame-root > .content-cards-3col,
  .frame-root > .video-module {
    width: 100%;
    margin-left: 0;
    margin-right: 0;
  }

  .frame-root > .lp-full-bleed .lp-full-bleed__inner {
    width: min(100%, var(--module-content-max-mobile));
  }

  :host([data-lp-page="lp-heros"]) .frame-root .hero-bleed-flex__content {
    padding-inline: 16px;
  }
}
"""


class LpSyncError(RuntimeError):
    pass


JSON_DECODER = json.JSONDecoder()


def fail(message: str) -> None:
    raise LpSyncError(message)


def read_text(path: Path) -> str:
    if not path.exists():
        fail(f"Fehlende Quelle: {path.relative_to(PROJECT_ROOT)}")
    return path.read_text(encoding="utf-8")


def write_text(path: Path, content: str) -> None:
    path.write_text(content, encoding="utf-8")


def normalize_text(value: str) -> str:
    return value.replace("\r\n", "\n").rstrip() + "\n"


def load_module_metadata() -> list[dict[str, str]]:
    try:
        payload = json.loads(read_text(MODULE_METADATA_PATH))
    except json.JSONDecodeError as exc:
        fail(f"{MODULE_METADATA_PATH.relative_to(PROJECT_ROOT)} ist kein gueltiges JSON: {exc}")

    modules = payload.get("modules")
    if not isinstance(modules, list) or not modules:
        fail("module-metadata.json enthaelt kein gueltiges, nicht-leeres 'modules'-Array.")

    module_ids: list[str] = []
    for index, module in enumerate(modules, start=1):
        if not isinstance(module, dict):
            fail(f"module-metadata.json: Eintrag #{index} ist kein Objekt.")
        for key in ["id", "label", "category", "source", "status"]:
            if key not in module or not isinstance(module[key], str) or not module[key].strip():
                fail(f"module-metadata.json: Modul #{index} fehlt ein gueltiges Feld '{key}'.")
        module_ids.append(module["id"])

    duplicates = sorted({item for item in module_ids if module_ids.count(item) > 1})
    if duplicates:
        fail(f"module-metadata.json enthaelt doppelte Modul-IDs: {', '.join(duplicates)}")

    return modules


def load_content_data_payload() -> tuple[str, str, str, dict[str, Any]]:
    text = read_text(CONTENT_DATA_PATH)
    marker_index = text.find(CONTENT_DATA_MARKER)
    if marker_index == -1:
        fail("content-data.js enthaelt keinen erwarteten window.designLibraryData-Assignment-Header.")

    payload_start = marker_index + len(CONTENT_DATA_MARKER)
    payload_end = text.rfind(";")
    if payload_end == -1 or payload_end < payload_start:
        fail("content-data.js enthaelt keinen gueltigen JSON-Assignment-Abschluss mit ';'.")

    payload = text[payload_start:payload_end].strip()
    try:
        content_data = json.loads(payload)
    except json.JSONDecodeError as exc:
        fail(f"content-data.js enthaelt kein gueltiges JSON-Payload: {exc}")

    if not isinstance(content_data, dict):
        fail("content-data.js enthaelt kein Objekt auf Top-Level.")

    return text[:payload_start], payload, text[payload_end:], content_data


def skip_json_whitespace(text: str, index: int) -> int:
    while index < len(text) and text[index] in " \t\r\n":
        index += 1
    return index


def find_object_member_value_span(text: str, object_start: int, object_end: int, key: str) -> tuple[int, int]:
    index = skip_json_whitespace(text, object_start)
    if index >= object_end or text[index] != "{":
        fail(f"Erwartetes JSON-Objekt fuer Schluessel '{key}' wurde nicht gefunden.")

    index += 1
    while index <= object_end:
        index = skip_json_whitespace(text, index)
        if index >= object_end:
            break
        if text[index] == "}":
            break

        parsed_key, key_end = JSON_DECODER.raw_decode(text, index)
        if not isinstance(parsed_key, str):
            fail(f"Unerwarteter JSON-Schluessel beim Suchen nach '{key}'.")

        index = skip_json_whitespace(text, key_end)
        if index >= object_end or text[index] != ":":
            fail(f"Unerwartetes JSON-Format beim Schluessel '{parsed_key}'.")

        index += 1
        value_start = skip_json_whitespace(text, index)
        _, value_end = JSON_DECODER.raw_decode(text, value_start)

        if parsed_key == key:
            return value_start, value_end

        index = skip_json_whitespace(text, value_end)
        if index < object_end and text[index] == ",":
            index += 1
            continue
        if index < object_end and text[index] == "}":
            break

    fail(f"content-data.js enthaelt keinen eindeutig bestimmbaren Objekt-Schluessel '{key}'.")


def line_indent_before(text: str, index: int) -> str:
    line_start = text.rfind("\n", 0, index) + 1
    line_prefix = text[line_start:index]
    whitespace_len = len(line_prefix) - len(line_prefix.lstrip(" \t"))
    return line_prefix[:whitespace_len]


def indent_multiline_value(value: str, indent: str) -> str:
    lines = value.splitlines()
    if len(lines) <= 1:
        return value
    return lines[0] + "\n" + "\n".join(f"{indent}{line}" if line else line for line in lines[1:])


def build_lp_content_section(
    metadata: list[dict[str, str]], existing_section: dict[str, Any] | None = None
) -> dict[str, Any]:
    active_modules = [module for module in metadata if module["status"] == "active"]
    if not active_modules:
        fail("module-metadata.json enthaelt keine aktiven LP-Module fuer content-data.js.")

    base_section: dict[str, Any] = dict(existing_section) if isinstance(existing_section, dict) else {}
    if not isinstance(base_section.get("label"), str) or not base_section["label"].strip():
        base_section["label"] = "LP Builder"

    active_module_ids = [module["id"] for module in active_modules]
    active_id_set = set(active_module_ids)
    metadata_by_id = {module["id"]: module for module in active_modules}

    mapped_ids: list[str] = []
    items: list[dict[str, Any]] = []
    for spec in LEGACY_LP_PAGE_SPECS:
        modules = spec["modules"]
        missing = [module_id for module_id in modules if module_id not in active_id_set]
        if missing:
            fail(
                "Legacy-LP-Seite "
                f"{spec['id']} referenziert unbekannte oder inaktive Module: {', '.join(missing)}"
            )

        mapped_ids.extend(modules)
        items.append(
            {
                "id": spec["id"],
                "label": spec["label"],
                "kind": "lpModules",
                "modules": modules,
            }
        )

    duplicate_mapped_ids = sorted({module_id for module_id in mapped_ids if mapped_ids.count(module_id) > 1})
    if duplicate_mapped_ids:
        fail(
            "Legacy-LP-Struktur enthaelt doppelt zugeordnete Module: "
            f"{', '.join(duplicate_mapped_ids)}"
        )

    unmapped_ids = [module_id for module_id in active_module_ids if module_id not in set(mapped_ids)]
    if unmapped_ids:
        labels = [metadata_by_id[module_id]["label"] for module_id in unmapped_ids]
        fail(
            "Aktive LP-Module sind in der Legacy-LP-Struktur nicht zugeordnet: "
            + ", ".join(f"{module_id} ({label})" for module_id, label in zip(unmapped_ids, labels))
        )

    base_section["items"] = items
    return base_section


def build_content_data_output(metadata: list[dict[str, str]]) -> str:
    prefix, payload, suffix, content_data = load_content_data_payload()

    sections = content_data.get("sections")
    if not isinstance(sections, dict):
        fail("content-data.js enthaelt keine erwartete sections-Struktur.")

    lp_section = sections.get("lp")
    if not isinstance(lp_section, dict):
        fail("content-data.js enthaelt keinen eindeutig aktualisierbaren sections.lp-Block.")

    top_start = skip_json_whitespace(payload, 0)
    top_end = len(payload)
    sections_start, sections_end = find_object_member_value_span(payload, top_start, top_end, "sections")
    lp_start, lp_end = find_object_member_value_span(payload, sections_start, sections_end, "lp")

    updated_lp_section = build_lp_content_section(metadata, lp_section)
    updated_lp_text = indent_multiline_value(
        json.dumps(updated_lp_section, ensure_ascii=False, indent=2),
        line_indent_before(payload, lp_start),
    )

    updated_payload = payload[:lp_start] + updated_lp_text + payload[lp_end:]
    try:
        reparsed = json.loads(updated_payload)
    except json.JSONDecodeError as exc:
        fail(f"Der aktualisierte LP-Block wuerde content-data.js ungueltig machen: {exc}")

    reparsed_lp = reparsed.get("sections", {}).get("lp")
    if reparsed_lp != updated_lp_section:
        fail("Der aktualisierte LP-Block in content-data.js konnte nicht stabil verifiziert werden.")

    return prefix + updated_payload + suffix


def extract_module_markup(module_ids: list[str]) -> dict[str, str]:
    text = read_text(COMPONENT_LIBRARY_PATH)
    lines = text.splitlines()
    start_prefix = "<!-- LP_MODULE_START: "
    end_prefix = "<!-- LP_MODULE_END: "

    tokens: list[tuple[str, str, int]] = []
    for lineno, line in enumerate(lines, start=1):
        stripped = line.strip()
        if stripped.startswith(start_prefix) and stripped.endswith(" -->"):
            tokens.append(("start", stripped[len(start_prefix) : -4], lineno))
        elif stripped.startswith(end_prefix) and stripped.endswith(" -->"):
            tokens.append(("end", stripped[len(end_prefix) : -4], lineno))

    if not tokens:
        fail("component-library.html enthaelt keine LP-Modulmarker.")

    seen_starts: set[str] = set()
    seen_ends: set[str] = set()
    current_module: str | None = None
    current_start_line = 0
    content_start_index = 0
    extracted: dict[str, str] = {}

    for kind, module_id, lineno in tokens:
        if kind == "start":
            if current_module is not None:
                fail(
                    "Verschachtelte LP-Modulmarker sind nicht erlaubt: "
                    f"Start '{module_id}' in Zeile {lineno} innerhalb von '{current_module}' "
                    f"(Start in Zeile {current_start_line})."
                )
            if module_id in seen_starts:
                fail(f"Doppelter LP_MODULE_START fuer '{module_id}' in Zeile {lineno}.")
            current_module = module_id
            current_start_line = lineno
            content_start_index = lineno
            seen_starts.add(module_id)
            continue

        if current_module is None:
            fail(f"LP_MODULE_END fuer '{module_id}' in Zeile {lineno} ohne passenden Startmarker.")
        if current_module != module_id:
            fail(
                f"Marker-Reihenfolgefehler: LP_MODULE_END '{module_id}' in Zeile {lineno} "
                f"passt nicht zum offenen Modul '{current_module}' aus Zeile {current_start_line}."
            )
        if module_id in seen_ends:
            fail(f"Doppelter LP_MODULE_END fuer '{module_id}' in Zeile {lineno}.")

        fragment = "\n".join(lines[content_start_index : lineno - 1]).strip()
        if not fragment:
            fail(f"Modul '{module_id}' zwischen Marker-Zeilen {current_start_line} und {lineno} ist leer.")
        extracted[module_id] = fragment
        seen_ends.add(module_id)
        current_module = None
        current_start_line = 0
        content_start_index = 0

    if current_module is not None:
        fail(f"LP_MODULE_START fuer '{current_module}' ohne passenden Endmarker.")

    marker_ids = set(extracted.keys())
    metadata_ids = set(module_ids)

    unknown_markers = sorted(marker_ids - metadata_ids)
    if unknown_markers:
        fail(
            "component-library.html enthaelt Marker ohne Metadaten in module-metadata.json: "
            + ", ".join(unknown_markers)
        )

    missing_markers = sorted(metadata_ids - marker_ids)
    if missing_markers:
        fail(
            "module-metadata.json enthaelt Modul-IDs ohne passende Marker in component-library.html: "
            + ", ".join(missing_markers)
        )

    return {module_id: extracted[module_id] for module_id in module_ids}


def build_lp_shadow_styles() -> str:
    css_chunks: list[str] = []

    legacy_css = read_text(LP_LEGACY_UTILITIES_PATH).strip()
    css_chunks.append(
        f"/* SOURCE: {LP_LEGACY_UTILITIES_PATH.relative_to(PROJECT_ROOT).as_posix()} */\n{legacy_css}"
    )

    for source in LP_CORE_STYLE_SOURCES:
        css = read_text(source).strip()
        css_chunks.append(f"/* SOURCE: {source.relative_to(PROJECT_ROOT).as_posix()} */\n{css}")

    css_chunks.append(
        "/* SOURCE: embedded LP preview frame styles for the Design Library */\n"
        + EMBEDDED_PREVIEW_FRAME_CSS.strip()
    )

    return "\n\n".join(css_chunks).strip() + "\n"


def render_markup_assignment(markup_map: dict[str, str]) -> str:
    body = json.dumps(markup_map, ensure_ascii=False, indent=2)
    return f"{GENERATED_HEADER}{LP_MARKUP_MARKER}{body};\n"


def render_shadow_assignment(shadow_css: str) -> str:
    body = json.dumps(shadow_css, ensure_ascii=False)
    return f"{GENERATED_CSS_HEADER}{LP_SHADOW_MARKER}{body};\n"


def generate_outputs() -> dict[Path, str]:
    metadata = load_module_metadata()
    module_ids = [module["id"] for module in metadata]
    markup_map = extract_module_markup(module_ids)
    shadow_css = build_lp_shadow_styles()
    content_data = build_content_data_output(metadata)

    if not markup_map:
        fail("lp-module-markup.js wurde leer generiert.")
    if not shadow_css.strip():
        fail("lp-shadow-styles.js wurde leer generiert.")

    return {
        CONTENT_DATA_PATH: content_data,
        LP_MARKUP_PATH: render_markup_assignment(markup_map),
        LP_SHADOW_STYLES_PATH: render_shadow_assignment(shadow_css),
    }


def check_outputs(outputs: dict[Path, str]) -> bool:
    drift_paths: list[Path] = []

    for path, expected in outputs.items():
        if not path.exists():
            drift_paths.append(path)
            continue
        actual = read_text(path)
        if normalize_text(actual) != normalize_text(expected):
            drift_paths.append(path)

    if not drift_paths:
        print("LP-Artefakte sind aktuell.")
        return True

    for path in drift_paths:
        print(f"DRIFT: {path.relative_to(PROJECT_ROOT)}")
    return False


def write_outputs(outputs: dict[Path, str]) -> None:
    for path, content in outputs.items():
        write_text(path, content)
        print(f"Aktualisiert: {path.relative_to(PROJECT_ROOT)}")


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="LP-Sync-Script fuer lp-builder -> design-system/design-library."
    )
    parser.add_argument(
        "--check",
        action="store_true",
        help="Zieldateien nur im Speicher berechnen und auf Drift pruefen.",
    )
    return parser.parse_args()


def main() -> int:
    args = parse_args()

    try:
        outputs = generate_outputs()
        if args.check:
            return 0 if check_outputs(outputs) else 1

        write_outputs(outputs)
        return 0
    except LpSyncError as exc:
        print(f"Fehler: {exc}", file=sys.stderr)
        return 2


if __name__ == "__main__":
    raise SystemExit(main())
