#!/usr/bin/env python3

from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path
from typing import Any

# LP-Sync laeuft kuenftig ueber das dedizierte LP-Sync-Script.
# Die hier verbleibende LP-Fallback-Logik ist Legacy und soll die allgemeinen
# Design-Library-Checks nicht an veraltete LP-Status-Texte binden.
from sync_lp_builder_to_design_library import (
    build_lp_content_section as build_lp_content_section_via_lp_sync,
    build_lp_shadow_styles as build_lp_shadow_styles_via_lp_sync,
    extract_module_markup as extract_lp_module_markup_via_lp_sync,
    load_module_metadata as load_lp_module_metadata_via_lp_sync,
    render_markup_assignment as render_lp_markup_assignment_via_lp_sync,
    render_shadow_assignment as render_lp_shadow_assignment_via_lp_sync,
)


PROJECT_ROOT = Path(__file__).resolve().parents[2]
DESIGN_LIBRARY_DIR = PROJECT_ROOT / "design-system" / "design-library"

CONTENT_DATA_PATH = DESIGN_LIBRARY_DIR / "content-data.js"
LP_MARKUP_PATH = DESIGN_LIBRARY_DIR / "lp-module-markup.js"
LP_SHADOW_STYLES_PATH = DESIGN_LIBRARY_DIR / "lp-shadow-styles.js"

TOKENS_PATH = PROJECT_ROOT / "design-system" / "tokens" / "brands" / "immoscout24.json"
SERVICE_PRODUCTS_PATH = PROJECT_ROOT / "email-builder" / "agent" / "service-products.json"
EMAIL_MODULES_DIR = PROJECT_ROOT / "email-builder" / "preview" / "modules"
LP_MODULES_DIR = PROJECT_ROOT / "lp-builder" / "preview" / "modules"

LP_SHADOW_STYLE_SOURCES = [
    PROJECT_ROOT / "design-system" / "design-library" / "lp-legacy-utilities.css",
    PROJECT_ROOT / "lp-builder" / "core-foundations.css",
    PROJECT_ROOT / "lp-builder" / "core-buttons.css",
    PROJECT_ROOT / "lp-builder" / "core-components.css",
    PROJECT_ROOT / "lp-builder" / "preview" / "frame-base.css",
]

LEGACY_CONTENT_DATA_MARKER = "window.frontifyStyleTestData = "
LEGACY_LP_MARKUP_MARKER = "window.frontifyStyleTestLpModuleMarkup = "
LEGACY_LP_SHADOW_MARKER = "window.frontifyStyleTestLpShadowCss = "

CONTENT_DATA_MARKER = "window.designLibraryData = "
LP_MARKUP_MARKER = "window.designLibraryLpModuleMarkup = "
LP_SHADOW_MARKER = "window.designLibraryLpShadowCss = "

GENERATED_HEADER = (
    "// Generated by design-system/scripts/sync_design_library_sources.py.\n"
    "// Do not edit manually.\n"
)


class SyncError(RuntimeError):
    pass


def fail(message: str) -> None:
    raise SyncError(message)


def read_text(path: Path) -> str:
    if not path.exists():
        fail(f"Fehlende Quelle: {path.relative_to(PROJECT_ROOT)}")
    return path.read_text(encoding="utf-8")


def write_text(path: Path, content: str) -> None:
    path.write_text(content, encoding="utf-8")


def load_assignment_json(path: Path, markers: list[str]) -> Any:
    text = read_text(path)
    marker_index = -1
    marker = ""
    for candidate in markers:
        marker_index = text.find(candidate)
        if marker_index >= 0:
            marker = candidate
            break
    if marker_index < 0:
        expected = ", ".join(repr(item) for item in markers)
        fail(f"{path.relative_to(PROJECT_ROOT)} enthaelt keinen erwarteten Marker ({expected}).")

    payload = text[marker_index + len(marker) :].strip()
    if payload.endswith(";"):
        payload = payload[:-1].rstrip()

    try:
        return json.loads(payload)
    except json.JSONDecodeError as exc:
        fail(f"{path.relative_to(PROJECT_ROOT)} konnte nicht als JSON-Assignment gelesen werden: {exc}")


def render_assignment(marker: str, payload: Any) -> str:
    body = json.dumps(payload, ensure_ascii=False, indent=2)
    return f"{GENERATED_HEADER}{marker}{body};\n"


def dump_assignment(path: Path, marker: str, payload: Any) -> None:
    write_text(path, render_assignment(marker, payload))


def strip_email_runtime(html: str, source: Path) -> str:
    cleaned = re.sub(
        r"\n?<script\b[^>]*\bsrc=\"\.\./token-runtime\.js\"[^>]*>\s*</script>\s*$",
        "",
        html.strip(),
        flags=re.S,
    ).strip()

    if "<script" in cleaned:
        fail(
            f"{source.relative_to(PROJECT_ROOT)} enthaelt unerwartete <script>-Tags und kann nicht sicher "
            "in content-data.js eingebettet werden."
        )

    return cleaned


def extract_frame_root_inner(html: str, source: Path) -> str:
    matches = list(
        re.finditer(
            r"<main\b[^>]*\bclass=\"frame-root\"[^>]*>(.*?)</main>",
            html,
            flags=re.S,
        )
    )
    if len(matches) != 1:
        fail(
            f"{source.relative_to(PROJECT_ROOT)} enthaelt {len(matches)} eindeutige "
            '<main class="frame-root">-Bloecke. Erwartet wurde genau 1.'
        )

    return matches[0].group(1).strip()


def indent_block(value: str, prefix: str) -> str:
    return "\n".join(f"{prefix}{line}" if line else line for line in value.splitlines())


def build_lp_module_markup() -> dict[str, str]:
    module_markup: dict[str, str] = {}
    module_files = sorted(LP_MODULES_DIR.glob("*.html")) if LP_MODULES_DIR.exists() else []
    if not module_files:
        fallback = load_assignment_json(
            LP_MARKUP_PATH,
            [LP_MARKUP_MARKER, LEGACY_LP_MARKUP_MARKER],
        )
        if not isinstance(fallback, dict) or not fallback:
            fail(
                "Es wurden keine LP-Preview-Module unter lp-builder/preview/modules/*.html gefunden "
                "und es liegt kein bestaetigtes LP-Artefakt in design-library/lp-module-markup.js vor."
            )
        return {str(key): str(value) for key, value in fallback.items()}

    for path in module_files:
        module_markup[path.stem] = extract_frame_root_inner(read_text(path), path)

    return module_markup


def build_lp_shadow_styles() -> str:
    missing_sources = [source for source in LP_SHADOW_STYLE_SOURCES if not source.exists()]
    if missing_sources:
        fallback = load_assignment_json(
            LP_SHADOW_STYLES_PATH,
            [LP_SHADOW_MARKER, LEGACY_LP_SHADOW_MARKER],
        )
        if not isinstance(fallback, str) or not fallback.strip():
            fail(
                "LP-CSS-Quellen fehlen und es liegt kein bestaetigtes LP-Artefakt in "
                "design-library/lp-shadow-styles.js vor."
            )
        return fallback

    chunks: list[str] = []
    for source in LP_SHADOW_STYLE_SOURCES:
        css = read_text(source).strip()
        chunks.append(f"/* SOURCE: {source.relative_to(PROJECT_ROOT).as_posix()} */\n{css}")
    return "\n\n".join(chunks)


def build_service_products() -> list[dict[str, str]]:
    payload = json.loads(read_text(SERVICE_PRODUCTS_PATH))
    products = payload.get("products")
    if not isinstance(products, list):
        fail("email-builder/agent/service-products.json enthaelt kein gueltiges 'products'-Array.")

    result: list[dict[str, str]] = []
    required_keys = ["id", "original_snippet_name", "title", "description", "icon_url", "target_url"]

    for index, product in enumerate(products, start=1):
        if not isinstance(product, dict):
            fail(f"service-products.json: Produkt #{index} ist kein Objekt.")
        missing = [key for key in required_keys if key not in product]
        if missing:
            fail(
                f"service-products.json: Produkt #{index} fehlt Pflichtfelder: {', '.join(missing)}."
            )

        result.append(
            {
                "id": str(product["id"]),
                "originalSnippetName": str(product["original_snippet_name"]),
                "title": str(product["title"]),
                "description": str(product["description"]),
                "iconUrl": str(product["icon_url"]),
                "targetUrl": str(product["target_url"]),
            }
        )

    return result


def build_email_modules_map() -> dict[str, str]:
    module_map: dict[str, str] = {}
    module_files = sorted(EMAIL_MODULES_DIR.glob("*.html"))
    if not module_files:
        fail("Es wurden keine E-Mail-Preview-Module unter email-builder/preview/modules/*.html gefunden.")

    for path in module_files:
        module_map[path.stem] = strip_email_runtime(read_text(path), path)

    return module_map


def build_tokens_snapshot(canonical_tokens: dict[str, Any], existing_tokens: dict[str, Any]) -> dict[str, Any]:
    tokens = dict(existing_tokens)

    shared_palette = canonical_tokens["colors"]["palette"]["shared"]
    lp_palette = canonical_tokens["colors"]["palette"]["lp"]
    email_palette = canonical_tokens["colors"]["palette"]["email"]
    button_variants = canonical_tokens["buttons"]["variants"]
    typography = canonical_tokens["typography"]

    tokens["colors"] = {
        "groups": [
            {
                "title": "LP Colors",
                "items": [
                    {"name": "Teal", "value": lp_palette["teal"]},
                    {"name": "Yellow", "value": lp_palette["yellow"]},
                    {"name": "Blue", "value": lp_palette["blue"]},
                    {"name": "Purple", "value": lp_palette["purple"]},
                    {"name": "Orange", "value": lp_palette["orange"]},
                ],
            },
            {
                "title": "E-Mail Colors",
                "items": [
                    {"name": "Teal", "value": email_palette["teal"]},
                    {"name": "Yellow", "value": email_palette["yellow"]},
                    {"name": "Blue", "value": email_palette["blue"]},
                    {"name": "Red", "value": email_palette["red"]},
                ],
            },
            {
                "title": "Grautoene",
                "items": [
                    {"name": "Charcoal", "value": shared_palette["charcoal"]},
                    {"name": "White", "value": shared_palette["white"]},
                    {"name": "Sand", "value": shared_palette["sand"]},
                    {"name": "Grey 1", "value": shared_palette["grey1"]},
                    {"name": "Grey 2", "value": shared_palette["grey2"]},
                    {"name": "Grey 3", "value": shared_palette["grey3"]},
                    {"name": "Grey 4", "value": shared_palette["grey4"]},
                    {"name": "Grey 5", "value": shared_palette["grey5"]},
                    {"name": "Grey 6", "value": shared_palette["grey6"]},
                ],
            },
        ]
    }

    manual_button_items = [
        item for item in existing_tokens.get("buttons", {}).get("items", []) if item.get("isLink")
    ]
    generated_button_items = []
    for name in canonical_tokens["buttons"]["canonical_types"]:
        variant = button_variants[name]["lp"]
        generated_button_items.append(
            {
                "name": name,
                "background": variant["default"]["background"].split("."),
                "color": variant["default"]["text"].split("."),
                "border": variant["default"]["border"].split("."),
                "hoverBackground": variant["hover"]["background"].split("."),
                "hoverColor": variant["hover"]["text"].split("."),
                "hoverBorder": variant["hover"]["border"].split("."),
                "isLink": False,
            }
        )

    def resolve_token_path(parts: list[str]) -> str:
        cursor: Any = canonical_tokens
        for part in parts:
            cursor = cursor[part]
        return str(cursor)

    for item in generated_button_items:
        item["background"] = resolve_token_path(item["background"])
        item["color"] = resolve_token_path(item["color"])
        item["border"] = resolve_token_path(item["border"])
        item["hoverBackground"] = resolve_token_path(item["hoverBackground"])
        item["hoverColor"] = resolve_token_path(item["hoverColor"])
        item["hoverBorder"] = resolve_token_path(item["hoverBorder"])

    tokens["buttons"] = {"items": generated_button_items + manual_button_items}

    tokens["typography"] = {
        "sample": existing_tokens["typography"]["sample"],
        "sourceLabel": existing_tokens["typography"]["sourceLabel"],
        "sourceUrl": existing_tokens["typography"]["sourceUrl"],
        "headingItems": [
            {
                "name": "heading-xxl",
                "label": "Heading XXL bold",
                "desktop": typography["heading"]["xxl"]["desktop"],
                "mobile": typography["heading"]["xxl"]["mobile"],
            },
            {
                "name": "heading-xl",
                "label": "Heading XL bold",
                "desktop": typography["heading"]["xl"]["desktop"],
                "mobile": typography["heading"]["xl"]["mobile"],
            },
            {
                "name": "heading-l",
                "label": "Heading L bold",
                "desktop": typography["heading"]["l"]["desktop"],
                "mobile": typography["heading"]["l"]["mobile"],
            },
            {
                "name": "heading-m",
                "label": "Heading M bold",
                "desktop": typography["heading"]["m"]["desktop"],
                "mobile": typography["heading"]["m"]["mobile"],
            },
            {
                "name": "heading-s",
                "label": "Heading S bold",
                "desktop": typography["heading"]["s"]["desktop"],
                "mobile": typography["heading"]["s"]["mobile"],
            },
            {
                "name": "heading-xs",
                "label": "Heading XS bold",
                "desktop": typography["heading"]["xs"]["desktop"],
                "mobile": typography["heading"]["xs"]["mobile"],
            },
        ],
        "bodyItems": [
            {
                "name": "body-standard",
                "label": "P Standard",
                "desktop": typography["body"]["standard"]["desktop"],
                "mobile": typography["body"]["standard"]["mobile"],
            },
            {
                "name": "body-tabular",
                "label": "P Tabular",
                "desktop": typography["body"]["tabular"]["desktop"],
                "mobile": typography["body"]["tabular"]["mobile"],
            },
            {
                "name": "body-hint",
                "label": "P Hint",
                "desktop": typography["body"]["hint"]["desktop"],
                "mobile": typography["body"]["hint"]["mobile"],
            },
        ],
    }

    tokens["radius"] = [
        {"name": "none", "value": canonical_tokens["radius"]["none"]},
        {"name": "2", "value": canonical_tokens["radius"]["2"]},
        {"name": "4", "value": canonical_tokens["radius"]["4"]},
        {"name": "8", "value": canonical_tokens["radius"]["8"]},
        {"name": "12", "value": canonical_tokens["radius"]["12"]},
        {"name": "16", "value": canonical_tokens["radius"]["16"]},
        {"name": "24", "value": canonical_tokens["radius"]["24"]},
        {"name": "40", "value": canonical_tokens["radius"]["40"]},
        {"name": "pill", "value": canonical_tokens["radius"]["pill"]},
    ]

    tokens["spacing"] = [
        {"name": "spacing-100", "value": canonical_tokens["spacing"]["100"]},
        {"name": "spacing-200", "value": canonical_tokens["spacing"]["200"]},
        {"name": "spacing-300", "value": canonical_tokens["spacing"]["300"]},
        {"name": "spacing-400", "value": canonical_tokens["spacing"]["400"]},
        {"name": "spacing-600", "value": canonical_tokens["spacing"]["600"]},
        {"name": "spacing-800", "value": canonical_tokens["spacing"]["800"]},
        {"name": "spacing-1000", "value": canonical_tokens["spacing"]["1000"]},
        {"name": "spacing-1500", "value": canonical_tokens["spacing"]["1500"]},
    ]

    tokens["borders"] = [
        {"name": "none", "value": canonical_tokens["borders"]["none"]},
        {"name": "thin", "value": canonical_tokens["borders"]["thin"]},
    ]

    tokens["ratios"] = existing_tokens["ratios"]
    return tokens


def build_email_library_html(item: dict[str, Any], email_modules: dict[str, str]) -> str:
    section_id = f"email-{item['id']}"
    rows: list[str] = []

    for module_name in item.get("modules", []):
        module_html = email_modules.get(module_name)
        if module_html is None:
            fail(
                f"content-data.js referenziert das E-Mail-Modul '{module_name}', "
                "aber unter email-builder/preview/modules wurde keine passende HTML-Datei gefunden."
            )

        indented_module_html = indent_block(module_html, "        ")
        rows.append(
            "\n".join(
                [
                    '  <div class="test-module-row">',
                    f'    <div class="module-copy" data-module="{module_name}">',
                    f'      <button class="module-copy__button" type="button" aria-label="{module_name} kopieren" title="{module_name} kopieren">',
                    f'        <span class="module-copy__name">{module_name}</span>',
                    '        <svg class="module-copy__icon module-copy__icon--default" viewBox="0 0 24 24"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"></rect><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"></path></svg>',
                    '        <span class="module-copy__icon--success" aria-hidden="true"></span>',
                    "      </button>",
                    "    </div>",
                    '    <div class="test-module-frame">',
                    f'      <div class="test-email-preview" data-email-preview-module="{module_name}">',
                    indented_module_html,
                    "      </div>",
                    "    </div>",
                    "  </div>",
                ]
            )
        )

    return "\n".join(
        [
            f'<section class="test-section" id="{section_id}">',
            "\n\n".join(rows),
            "</section>",
        ]
    )


EMAIL_SECTION_LABELS = {
    "heros-left": "Hero Left Aligned",
    "heros-center": "Hero Centered",
    "heros-fakeforms": "Fake Forms",
    "servicetiles": "Service Tiles",
}


def build_service_products_library_html(item: dict[str, Any], email_modules: dict[str, str]) -> str:
    module_name = "servicetiles"
    module_html = email_modules.get(module_name)
    if module_html is None:
        fail(
            "Der Service-Tiles-Bereich referenziert das E-Mail-Modul 'servicetiles', "
            "aber unter email-builder/preview/modules wurde keine passende HTML-Datei gefunden."
        )

    indented_module_html = indent_block(module_html, "                  ")
    return "\n".join(
        [
            '<section class="test-section" id="email-servicetiles">',
            '            <div class="test-module-row">',
            '              <div class="test-module-frame">',
            '                <div class="email-service-library">',
            '                  <div class="test-email-preview" data-email-preview-module="servicetiles">',
            indented_module_html,
            '                  </div>',
            '                </div>',
            '              </div>',
            '            </div>',
            '          </section>',
        ]
    )


def update_content_data() -> dict[str, Any]:
    content_data = load_assignment_json(
        CONTENT_DATA_PATH,
        [CONTENT_DATA_MARKER, LEGACY_CONTENT_DATA_MARKER],
    )
    if not isinstance(content_data, dict):
        fail("content-data.js enthaelt kein Objekt auf Top-Level.")

    if "sections" not in content_data or "email" not in content_data["sections"]:
        fail("content-data.js enthaelt keine erwartete sections.email-Struktur.")
    if "tokens" not in content_data:
        fail("content-data.js enthaelt kein erwartetes tokens-Feld.")

    canonical_tokens = json.loads(read_text(TOKENS_PATH))
    email_modules = build_email_modules_map()
    service_products = build_service_products()

    content_data["tokens"] = build_tokens_snapshot(canonical_tokens, content_data["tokens"])
    content_data["emailModules"] = email_modules
    content_data["serviceProducts"] = service_products
    content_data.pop("lpModuleBasePath", None)

    home_page = content_data.get("homePage")
    if isinstance(home_page, dict):
        home_page["label"] = "Design Library"
        home_page["intro"] = (
            "Die Library ist die zentrale Quelle fuer die GPT Builder. "
            "Sie buendelt Design Tokens, E-Mail-Builder-Module und LP-Builder-Module "
            "und dient als Referenz fuer konsistente Builder-Ausgaben."
        )
        home_page["quickLinks"] = [
            {
                "label": "E-Mail Builder",
                "section": "email",
                "text": "Module, Templates und Preview-Bausteine fuer den E-Mail-Bereich.",
                "gptLabel": "E-Mail Builder öffnen",
                "gptHref": "https://chatgpt.com/g/g-69c248087a7c819188ed0fe9f4ee2e14-e-mail-builder-beta",
            },
            {
                "label": "LP Builder",
                "section": "lp",
                "text": "Landingpage-Module aus den synchronisierten LP-Artefakten.",
                "gptLabel": "LP Builder öffnen",
                "gptHref": "https://chatgpt.com/g/g-69839550ac988191bd3a3838d2b00d02-landing-page-builder",
            },
        ]
        home_page.pop("note", None)
        home_page.pop("sections", None)

    lp_section = content_data.get("sections", {}).get("lp")
    if isinstance(lp_section, dict):
        lp_section["label"] = "LP Builder"

    email_items = content_data["sections"]["email"].get("items")
    if not isinstance(email_items, list):
        fail("content-data.js enthaelt kein gueltiges sections.email.items-Array.")

    for item in email_items:
        if not isinstance(item, dict) or "kind" not in item:
            fail("content-data.js enthaelt ein unerwartetes sections.email-Item.")

        item_id = item.get("id")
        if isinstance(item_id, str) and item_id in EMAIL_SECTION_LABELS:
            item["label"] = EMAIL_SECTION_LABELS[item_id]

        kind = item["kind"]
        if kind == "emailModules":
            item["libraryHtml"] = build_email_library_html(item, email_modules)
        elif kind == "serviceProducts":
            item.pop("note", None)
            item["libraryHtml"] = build_service_products_library_html(item, email_modules)
        else:
            fail(
                f"content-data.js enthaelt ein unbekanntes sections.email.kind '{kind}'. "
                "Teilgenerierung wird zur Sicherheit abgebrochen."
            )

    return content_data


def validate_design_library_compatibility(
    content_data: dict[str, Any], lp_markup: dict[str, str], shadow_css: str
) -> None:
    required_top_level_keys = ["homePage", "sections", "tokens", "serviceProducts"]
    for key in required_top_level_keys:
        if key not in content_data:
            fail(f"Die generierte content-data.js fehlt am Top-Level das erwartete Feld '{key}'.")

    if not isinstance(content_data["sections"].get("email", {}).get("items"), list):
        fail("Die generierte content-data.js fehlt sections.email.items.")
    if not isinstance(content_data["sections"].get("lp", {}).get("items"), list):
        fail("Die generierte content-data.js fehlt sections.lp.items.")
    if not isinstance(content_data.get("serviceProducts"), list):
        fail("Die generierte content-data.js fehlt ein gueltiges serviceProducts-Array.")
    if not isinstance(lp_markup, dict) or not lp_markup:
        fail("lp-module-markup.js wurde leer generiert.")
    if not shadow_css.strip():
        fail("lp-shadow-styles.js wurde leer generiert.")


def generate_outputs() -> dict[Path, str]:
    content_data = update_content_data()
    lp_metadata = load_lp_module_metadata_via_lp_sync()
    content_data["sections"]["lp"] = build_lp_content_section_via_lp_sync(
        lp_metadata,
        content_data.get("sections", {}).get("lp"),
    )
    lp_markup = extract_lp_module_markup_via_lp_sync([module["id"] for module in lp_metadata])
    lp_shadow_css = build_lp_shadow_styles_via_lp_sync()

    validate_design_library_compatibility(content_data, lp_markup, lp_shadow_css)

    return {
        CONTENT_DATA_PATH: render_assignment(CONTENT_DATA_MARKER, content_data),
        LP_MARKUP_PATH: render_lp_markup_assignment_via_lp_sync(lp_markup),
        LP_SHADOW_STYLES_PATH: render_lp_shadow_assignment_via_lp_sync(lp_shadow_css),
    }


def sync() -> None:
    rendered_outputs = generate_outputs()
    for path, content in rendered_outputs.items():
        write_text(path, content)

    print("Design-Library-Artefakte synchronisiert.")
    print(f"- {CONTENT_DATA_PATH.relative_to(PROJECT_ROOT)}")
    print(f"- {LP_MARKUP_PATH.relative_to(PROJECT_ROOT)}")
    print(f"- {LP_SHADOW_STYLES_PATH.relative_to(PROJECT_ROOT)}")


def check() -> None:
    rendered_outputs = generate_outputs()
    drifted_paths: list[Path] = []

    for path, expected_content in rendered_outputs.items():
        current_content = read_text(path)
        if current_content != expected_content:
            drifted_paths.append(path)

    if drifted_paths:
        print("Design-Library-Artefakte sind nicht aktuell.", file=sys.stderr)
        for path in drifted_paths:
            print(f"- {path.relative_to(PROJECT_ROOT)}", file=sys.stderr)
        raise SystemExit(1)

    print("Design-Library-Artefakte sind aktuell.")


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Synchronisiert oder prueft die generierten Artefakte der offiziellen design-system/design-library/."
    )
    parser.add_argument(
        "--check",
        action="store_true",
        help="Vergleicht die generierten Inhalte nur im Speicher und schreibt keine Dateien.",
    )
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    try:
        if args.check:
            check()
        else:
            sync()
    except SyncError as exc:
        print(f"Fehler: {exc}", file=sys.stderr)
        return 1
    except SystemExit as exc:
        code = exc.code if isinstance(exc.code, int) else 1
        return code
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
